### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'pop' of undefined

### ISSUE THREAD

**Issue by mvndaai** [mvndaai/testrail-promise#6]
When using the helper function: ifNeededCreateThenAddResultForCase() sometimes there is a pop error. It was mentioned in issue #5

**Comment by mvndaai** [comment]
This is the error
> Unhandled rejection TypeError: Cannot read property 'pop' of undefined
at xxx\testrail-promise\lib\helpers.js:88:41
at tryCatcher (xxx\testrail-promise\node_modules\bluebird\js\main\util.js:26:23)
at Promise._settlePromiseFromHandler (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:510:31)
at Promise._settlePromiseAt (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:584:18)
at Promise._settlePromises (xxx\testrail-promise\node_modules\bluebird\js\main\promise.js:700:14)
at Async._drainQueue (xxx\testrail-promise\node_modules\bluebird\js\main\async.js:123:16)
at Async._drainQueues (xxx\testrail-promise\node_modules\bluebird\js\main\async.js:133:10)
at Immediate.Async.drainQueues as _onImmediate
at processImmediate as _immediateCallback

**Comment by mvndaai** [comment]
I finally found this problem. It was when it could not find the "plan_id". It now errors gracefully. Thank you! https://github.com/mvndaai/testrail-promise/commit/a295a7cd21cd693773e88974a523cf66d365ced2
